import { chromium } from '@playwright/test';
const browser = await chromium.launch({ channel: 'chromium' });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
await page.goto('http://127.0.0.1:5188/?godmode=1', { waitUntil: 'domcontentloaded' });
await page.waitForFunction(() => !document.querySelector('#start-button')?.disabled, null, { timeout: 90_000 });
await page.evaluate(() => window.__THREE_GAME_TEST_HOOKS__?.setState('stress'));
await page.waitForTimeout(5000);
const rows = await page.evaluate(() => window.__THREE_GAME_TEST_HOOKS__?.sceneCensus());
for (const r of rows.slice(0, 14)) console.log(`${r.root.padEnd(28)} meshes=${String(r.meshes).padStart(4)} visible=${String(r.visible).padStart(4)} tris=${(r.tris/1000).toFixed(0)}k`);
await browser.close();
